substitutions:
  device_suffix: uno
  wifi_ssid: !secret WIFI_SSID
  wifi_password: !secret WIFI_PASSWORD

packages:
  dimled.mini: github://tqlabs-in/dimled-mini/esphome/device/base.yaml@main
  # dimled.mini:
  #   url: https://github.com/tqlabs-in/dimled-mini
  #   files: [esphome/device/base.yaml]
  #   ref: main
  #   refresh: always
