web_server:
  port: 80
  log: false
  # js_url: https://raw.githubusercontent.com/tqlabs-in/dimled-mini/refs/heads/main/esphome/device/web-server/www.js
  js_url: https://oi.esphome.io/v2/www.js
  css_url: ""
