---
defaults:
  led_builtin_id: led_builtin

esphome:
  on_boot:
    - priority: 350
      then:
        - light.turn_on:
            id: $led_builtin_id
            effect: blink

wifi:
  on_connect:
    then:
      - light.turn_on:
          id: $led_builtin_id
          effect: "None"
      - delay: 2ms
      - light.turn_off:
          id: $led_builtin_id
  on_disconnect:
    then:
      - light.turn_on:
          id: $led_builtin_id
          effect: blink
